export enum CacheSetting {
  MENU_LIST = "MENU_LIST",
  LOCAL_CACHE_KEY = "LOCAL_CACHE_KEY",
  SESSION_CACHE_KEY = "SESSION_CACHE_KEY",
  TOKEN_KEY = "TOKEN_KEY",
  USER_INFO_KEY = "USER_INFO_KEY",
  SESSION = "SESSION",
  LOCAL = "LOCAL",
}
